#!/bin/sh
# Copyright (C) 2023 muink
#
OOKLA_SPEEDTEST='/usr/libexec/netspeedtest/speedtest'
SPEEDTEST_RESULT='/var/speedtest_result'
# uci
CONFIG_NAME='netspeedtest'
NAMEDDSECTION='config'
 
# Ensure Ookla CLI exists
if [ ! -x "$OOKLA_SPEEDTEST" ]; then
	echo "Test failed" > "$SPEEDTEST_RESULT"
	exit 1
fi
 
# Prevent concurrent runs
[ -n "$(pgrep -f "$OOKLA_SPEEDTEST")" ] && exit 1
 
# Proxy support
if [ "$(uci -q get $CONFIG_NAME.$NAMEDDSECTION.proxy_enabled)" = "1" ]; then
	export ALL_PROXY="$(uci -q get $CONFIG_NAME.$NAMEDDSECTION.proxy_protocol)://$(uci -q get $CONFIG_NAME.$NAMEDDSECTION.proxy_server)"
fi
 
echo "Testing" > "$SPEEDTEST_RESULT"
result=$("$OOKLA_SPEEDTEST" --accept-gdpr --accept-license --progress=no 2>/dev/null | grep 'www.speedtest.net/result/' | sed -E 's|.+(://www.speedtest.net/\S+).*|https\1|;s|(\.png)$||')
[ -n "$result" ] && echo "$result" > "$SPEEDTEST_RESULT" || echo "Test failed" > "$SPEEDTEST_RESULT"
